[server]
# Configuration du serveur Streamlit
port = 8501
address = "0.0.0.0"

[theme]
# Thème de l'application
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
# Configuration du navigateur
gatherUsageStats = false